export const PERMISSIONS = Object.freeze({
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_UPDATE_ALL: "USER_UPDATE_ALL",
  USER_ASSIGN_ROLES: "USER_ASSIGN_ROLES",
  POLICY_CREATE: "POLICY_CREATE",
  POLICY_VIEW_ALL: "POLICY_VIEW_ALL",
  AMENDMENT_APPROVE: "AMENDMENT_APPROVE",
  REDUCTION_APPROVE: "REDUCTION_APPROVE",
  CLAIM_APPROVE: "CLAIM_APPROVE"
});